// Code generated by "stringer -type=Opcode"; DO NOT EDIT.

package code

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpConstant-0]
	_ = x[OpAdd-1]
	_ = x[OpSub-2]
	_ = x[OpMul-3]
	_ = x[OpDiv-4]
	_ = x[OpPop-5]
	_ = x[OpTrue-6]
	_ = x[OpFalse-7]
	_ = x[OpEqual-8]
	_ = x[OpNotEqual-9]
	_ = x[OpGreaterThan-10]
	_ = x[OpGreaterEqual-11]
	_ = x[OpLessThan-12]
	_ = x[OpLessEqual-13]
	_ = x[OpNegate-14]
	_ = x[OpNot-15]
	_ = x[OpJump-16]
	_ = x[OpJumpFalse-17]
	_ = x[OpNull-18]
	_ = x[OpGetGlobal-19]
	_ = x[OpSetGlobal-20]
	_ = x[OpGetLocal-21]
	_ = x[OpSetLocal-22]
	_ = x[OpArray-23]
	_ = x[OpObject-24]
	_ = x[OpIndex-25]
	_ = x[OpCall-26]
	_ = x[OpReturnValue-27]
	_ = x[OpReturn-28]
	_ = x[OpGetBuiltin-29]
	_ = x[OpClosure-30]
	_ = x[OpGetFree-31]
	_ = x[OpCurrentClosure-32]
	_ = x[OpSetProp-33]
	_ = x[OpGetProp-34]
	_ = x[OpAssign-35]
}

const _Opcode_name = "OpConstantOpAddOpSubOpMulOpDivOpPopOpTrueOpFalseOpEqualOpNotEqualOpGreaterThanOpGreaterEqualOpLessThanOpLessEqualOpNegateOpNotOpJumpOpJumpFalseOpNullOpGetGlobalOpSetGlobalOpGetLocalOpSetLocalOpArrayOpObjectOpIndexOpCallOpReturnValueOpReturnOpGetBuiltinOpClosureOpGetFreeOpCurrentClosureOpSetPropOpGetPropOpAssign"

var _Opcode_index = [...]uint16{0, 10, 15, 20, 25, 30, 35, 41, 48, 55, 65, 78, 92, 102, 113, 121, 126, 132, 143, 149, 160, 171, 181, 191, 198, 206, 213, 219, 232, 240, 252, 261, 270, 286, 295, 304, 312}

func (i Opcode) String() string {
	if i >= Opcode(len(_Opcode_index)-1) {
		return "Opcode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Opcode_name[_Opcode_index[i]:_Opcode_index[i+1]]
}
