// Code generated by "stringer -type Type -trimprefix type"; DO NOT EDIT.

package object

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeInt-0]
	_ = x[TypeBool-1]
	_ = x[TypeString-2]
	_ = x[TypeArray-3]
	_ = x[TypeObject-4]
}

const _Type_name = "TypeIntTypeBoolTypeStringTypeArrayTypeObject"

var _Type_index = [...]uint8{0, 7, 15, 25, 34, 44}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
