// Code generated by "stringer -type TokenType -trimprefix tokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Var-0]
	_ = x[Const-1]
	_ = x[Let-2]
	_ = x[Number-3]
	_ = x[String-4]
	_ = x[Boolean-5]
	_ = x[Null-6]
	_ = x[Undefined-7]
	_ = x[True-8]
	_ = x[False-9]
	_ = x[Identifier-10]
	_ = x[If-11]
	_ = x[Else-12]
	_ = x[Return-13]
	_ = x[For-14]
	_ = x[While-15]
	_ = x[Object-16]
	_ = x[Function-17]
	_ = x[Comma-18]
	_ = x[Colon-19]
	_ = x[Semicolon-20]
	_ = x[Plus-21]
	_ = x[PlusPlus-22]
	_ = x[Minus-23]
	_ = x[MinusMinus-24]
	_ = x[PlusEqual-25]
	_ = x[MinusEqual-26]
	_ = x[Star-27]
	_ = x[StarEqual-28]
	_ = x[StarStar-29]
	_ = x[Slash-30]
	_ = x[SlashSlash-31]
	_ = x[SlashEqual-32]
	_ = x[SlashStar-33]
	_ = x[Question-34]
	_ = x[QuestionDot-35]
	_ = x[Ampersand-36]
	_ = x[AmpersandAmpersand-37]
	_ = x[Bar-38]
	_ = x[BarBar-39]
	_ = x[Tilde-40]
	_ = x[Dot-41]
	_ = x[DotDotDot-42]
	_ = x[Bang-43]
	_ = x[BangEqual-44]
	_ = x[Equal-45]
	_ = x[EqualEqual-46]
	_ = x[EqualEqualEqual-47]
	_ = x[EqualGreater-48]
	_ = x[Greater-49]
	_ = x[GreaterEqual-50]
	_ = x[GreaterGreater-51]
	_ = x[GreaterGreaterGreater-52]
	_ = x[GreaterGreaterEqual-53]
	_ = x[Less-54]
	_ = x[LessLess-55]
	_ = x[LessLessLess-56]
	_ = x[LessEqual-57]
	_ = x[LessLessEqual-58]
	_ = x[LeftParenthesis-59]
	_ = x[RightParenthesis-60]
	_ = x[LeftBracket-61]
	_ = x[RightBracket-62]
	_ = x[LeftSquareBracket-63]
	_ = x[RightSquareBracket-64]
	_ = x[Error-65]
	_ = x[Throw-66]
	_ = x[New-67]
	_ = x[This-68]
	_ = x[Super-69]
	_ = x[Class-70]
	_ = x[EOF-71]
}

const _TokenType_name = "VarConstLetNumberStringBooleanNullUndefinedTrueFalseIdentifierIfElseReturnForWhileObjectFunctionCommaColonSemicolonPlusPlusPlusMinusMinusMinusPlusEqualMinusEqualStarStarEqualStarStarSlashSlashSlashSlashEqualSlashStarQuestionQuestionDotAmpersandAmpersandAmpersandBarBarBarTildeDotDotDotDotBangBangEqualEqualEqualEqualEqualEqualEqualEqualGreaterGreaterGreaterEqualGreaterGreaterGreaterGreaterGreaterGreaterGreaterEqualLessLessLessLessLessLessLessEqualLessLessEqualLeftParenthesisRightParenthesisLeftBracketRightBracketLeftSquareBracketRightSquareBracketErrorThrowNewThisSuperClassEOF"

var _TokenType_index = [...]uint16{0, 3, 8, 11, 17, 23, 30, 34, 43, 47, 52, 62, 64, 68, 74, 77, 82, 88, 96, 101, 106, 115, 119, 127, 132, 142, 151, 161, 165, 174, 182, 187, 197, 207, 216, 224, 235, 244, 262, 265, 271, 276, 279, 288, 292, 301, 306, 316, 331, 343, 350, 362, 376, 397, 416, 420, 428, 440, 449, 462, 477, 493, 504, 516, 533, 551, 556, 561, 564, 568, 573, 578, 581}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
