// Code generated by "stringer -type SymbolScope -trimprefix symboleScope"; DO NOT EDIT.

package compiler

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GlobalScope-0]
	_ = x[LocalScope-1]
}

const _SymbolScope_name = "GlobalScopeLocalScope"

var _SymbolScope_index = [...]uint8{0, 11, 21}

func (i SymbolScope) String() string {
	if i < 0 || i >= SymbolScope(len(_SymbolScope_index)-1) {
		return "SymbolScope(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SymbolScope_name[_SymbolScope_index[i]:_SymbolScope_index[i+1]]
}
