// Code generated by "stringer -type=ExceptionType"; DO NOT EDIT.

package coldmoon

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EvalError-0]
	_ = x[RangeError-1]
	_ = x[ReferenceError-2]
	_ = x[SyntaxError-3]
	_ = x[TypeError-4]
	_ = x[URIError-5]
}

const _ExceptionType_name = "EvalErrorRangeErrorReferenceErrorSyntaxErrorTypeErrorURIError"

var _ExceptionType_index = [...]uint8{0, 9, 19, 33, 44, 53, 61}

func (i ExceptionType) String() string {
	if i < 0 || i >= ExceptionType(len(_ExceptionType_index)-1) {
		return "ExceptionType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ExceptionType_name[_ExceptionType_index[i]:_ExceptionType_index[i+1]]
}
