package coldmoon

type Intrinsics struct {
	// %Object.Prototype%
	ObjectPrototype ObjectType
	// %Object%
	ObjectConstructor ObjectType
	// %Function.Prototype%
	FunctionPrototype ObjectType
	// %Function%
	FunctionConstructor ObjectType
	// %Array%
	ArrayConstructor ObjectType
	// %Array.Prototype%
	ArrayPrototype ObjectType
	// %ArrayIteratorPrototype%
	ArrayIteratorPrototype ObjectType
	// %Array.prototype.values%
	ArrayPrototypeValues ObjectType
	// %Boolean.Prototype%
	BooleanPrototype *BooleanObject
	// %Boolean%
	BooleanConstructor ObjectType
	// %String.Prototype%
	StringPrototype *StringObject
	// %String%
	StringConstructor ObjectType
	// %GeneratorFunction%
	GeneratorFunctionConstructor ObjectType
	// %GeneratorFunction.prototype%
	GeneratorFunctionPrototype ObjectType
	// %GeneratorFunction.prototype.prototype%
	GeneratorFunctionPrototypePrototype ObjectType
	// %AsyncGeneratorFunction%
	AsyncGeneratorFunction ObjectType
	// %AsyncGeneratorFunction.prototype%
	AsyncGeneratorFunctionPrototype ObjectType
	// %AsyncGeneratorFunction.prototype.prototype%
	AsyncGeneratorFunctionPrototypePrototype ObjectType
	// %AsyncIteratorPrototype%
	AsyncIteratorPrototype ObjectType
	// %AsyncFunction%
	AsyncFunctionConstructor ObjectType
	// %AsyncFunction.prototype%
	AsyncFunctionPrototype ObjectType
	// %Promise%
	Promise ObjectType
	// %Promise.prototype%
	PromisePrototype ObjectType
	// %Date.Prototype%
	DatePrototype ObjectType
	// %Date%
	DateConstructor ObjectType
	// %StringIteratorPrototype%
	StringIteratorPrototype ObjectType
	// %Number.Prototype%
	NumberPrototype *NumberObject
	// %Number%
	NumberConstructor ObjectType
	// &Symbol.Prototype%
	SymbolPrototype ObjectType
	// %Symbol%
	SymbolConstructor ObjectType
	// %BigInt.Prototype%
	BigIntPrototype ObjectType
	// %BigInt%
	BigIntConstructor ObjectType
	// %Reflect%
	Reflect ObjectType
	// %Proxy%
	Proxy ObjectType
	// %IteratorPrototype%
	IteratorPrototype ObjectType
	// %Math%
	Math ObjectType
	// %Map%
	Map ObjectType
	// %Map.prototype%
	MapPrototype ObjectType
	// %MapIteratorPrototype%
	MapIteratorPrototype ObjectType
	// %SetObject%
	Set ObjectType
	// %SetObject.prototype%
	SetPrototype ObjectType
	// %SetIteratorPrototype%
	SetIteratorPrototype ObjectType
	// %IsFinite%
	IsFinite ObjectType
	// %isNaN%
	IsNaN ObjectType
	// %eval%
	Eval ObjectType
	// %EvalError%
	EvalErrorConstructor ObjectType
	// %EvalError.prototype%
	EvalErrorPrototype ObjectType
	// %RangeError%
	RangeErrorConstructor ObjectType
	// %RangeError.prototype%
	RangeErrorPrototype ObjectType
	// %ReferenceError%
	ReferenceErrorConstructor ObjectType
	// %ReferenceError.prototype%
	ReferenceErrorPrototype ObjectType
	// %SyntaxError%
	SyntaxErrorConstructor ObjectType
	// %SyntaxError.prototype%
	SyntaxErrorPrototype ObjectType
	// %TypeError%
	TypeErrorConstructor ObjectType
	// %TypeError.prototype%
	TypeErrorPrototype ObjectType
	// %URIError%
	URIErrorConstructor ObjectType
	// %URIError.prototype%
	URIErrorPrototype ObjectType
	// %Error%
	ErrorConstructor ObjectType
	// %Error.prototype%
	ErrorPrototype ObjectType
	// %ThrowTypeError%
	ThrowTypeError ObjectType
	// %AggregateError%
	AggregateErrorConstructor ObjectType
	// %AggregateError.prototype%
	AggregateErrorPrototype ObjectType
}

func (i *Intrinsics) Get(key string) ObjectType {
	switch key {
	case "%Object.Prototype%":
		return i.ObjectPrototype
	case "%Object%":
		return i.ObjectConstructor
	case "%Function.Prototype%":
		return i.FunctionPrototype
	case "%Function%":
		return i.FunctionConstructor
	case "%Boolean.Prototype%":
		return i.BooleanPrototype
	case "%Boolean%":
		return i.BooleanConstructor
	case "%IsFinite%":
		return i.IsFinite
	case "%isNaN%":
		return i.IsNaN
	case "%eval%":
		return i.Eval
	case "%ThrowTypeError%":
		return i.ThrowTypeError
	case "%Array%":
		return i.ArrayConstructor
	case "%Array.Prototype%":
		return i.ArrayPrototype
	case "%String.Prototype%":
		return i.StringPrototype
	case "%String%":
		return i.StringConstructor
	case "%Number.Prototype%":
		return i.NumberPrototype
	case "%Number%":
		return i.NumberConstructor
	case "%Symbol.Prototype%":
		return i.SymbolPrototype
	case "%Symbol%":
		return i.SymbolConstructor
	case "%BigInt.Prototype%":
		return i.BigIntPrototype
	case "%BigInt%":
		return i.BigIntConstructor

	case "%EvalError%":
		return i.EvalErrorConstructor
	case "%EvalError.prototype%":
		return i.EvalErrorPrototype
	case "%RangeError%":
		return i.RangeErrorConstructor
	case "%RangeError.prototype%":
		return i.RangeErrorPrototype
	case "%ReferenceError%":
		return i.ReferenceErrorConstructor
	case "%ReferenceError.prototype%":
		return i.ReferenceErrorPrototype
	case "%SyntaxError%":
		return i.SyntaxErrorConstructor
	case "%SyntaxError.prototype%":
		return i.SyntaxErrorPrototype
	case "%TypeError%":
		return i.TypeErrorConstructor
	case "%TypeError.prototype%":
		return i.TypeErrorPrototype
	case "%URIError%":
		return i.URIErrorConstructor
	case "%URIError.prototype%":
		return i.URIErrorPrototype
	case "%Error%":
		return i.ErrorConstructor
	case "%Error.prototype%":
		return i.ErrorPrototype
	case "%AggregateError%":
		return i.AggregateErrorConstructor
	case "%AggregateError.prototype%":
		return i.AggregateErrorPrototype

	}
	panic("unknown intrinsic")
}
