package coldmoon

type Intrinsics struct {
	// %Object.Prototype%
	ObjectPrototype ObjectType
	// %Object%
	ObjectConstructor ObjectType
	// %Function.Prototype%
	FunctionPrototype ObjectType
	// %Function%
	FunctionConstructor ObjectType
	// %Array%
	ArrayConstructor ObjectType
	// %Array.Prototype%
	ArrayPrototype ObjectType
	// %ArrayIteratorPrototype%
	ArrayIteratorPrototype ObjectType
	// %Array.prototype.values%
	ArrayPrototypeValues ObjectType
	// %ArrayBuffer.prototype%
	ArrayBufferPrototype ObjectType
	// %ArrayBuffer%
	ArrayBufferConstructor ObjectType
	// %Boolean.Prototype%
	BooleanPrototype *BooleanObject
	// %Boolean%
	BooleanConstructor ObjectType
	// %String.Prototype%
	StringPrototype *StringObject
	// %String%
	StringConstructor ObjectType
	// %GeneratorFunction%
	GeneratorFunctionConstructor ObjectType
	// %GeneratorFunction.prototype%
	GeneratorFunctionPrototype ObjectType
	// %GeneratorFunction.prototype.prototype%
	GeneratorFunctionPrototypePrototype ObjectType
	// %DataView.prototype%
	DataViewPrototype ObjectType
	// %DataView%
	DataViewConstructor ObjectType
	// %AsyncGeneratorFunction%
	AsyncGeneratorFunction ObjectType
	// %AsyncGeneratorFunction.prototype%
	AsyncGeneratorFunctionPrototype ObjectType
	// %AsyncGeneratorFunction.prototype.prototype%
	AsyncGeneratorFunctionPrototypePrototype ObjectType
	// %AsyncIteratorPrototype%
	AsyncIteratorPrototype ObjectType
	// %AsyncFunction%
	AsyncFunctionConstructor ObjectType
	// %AsyncFunction.prototype%
	AsyncFunctionPrototype ObjectType
	// %Promise%
	Promise ObjectType
	// %Promise.prototype%
	PromisePrototype ObjectType
	// %Date.Prototype%
	DatePrototype ObjectType
	// %Date%
	DateConstructor ObjectType
	// %StringIteratorPrototype%
	StringIteratorPrototype ObjectType
	// %Number.Prototype%
	NumberPrototype *NumberObject
	// %Number%
	NumberConstructor ObjectType
	// &Symbol.Prototype%
	SymbolPrototype ObjectType
	// %Symbol%
	SymbolConstructor ObjectType
	// %BigInt.Prototype%
	BigIntPrototype ObjectType
	// %BigInt%
	BigIntConstructor ObjectType
	// %JSON%
	JSON ObjectType
	// %Reflect%
	Reflect ObjectType
	// %Proxy%
	Proxy ObjectType
	// %IteratorPrototype%
	IteratorPrototype ObjectType
	// %Math%
	Math ObjectType
	// %Map%
	Map ObjectType
	// %Map.prototype%
	MapPrototype ObjectType
	// %MapIteratorPrototype%
	MapIteratorPrototype ObjectType
	// %SetObject%
	Set ObjectType
	// %SetObject.prototype%
	SetPrototype ObjectType
	// %SetIteratorPrototype%
	SetIteratorPrototype ObjectType
	// %Intl%
	Intl ObjectType
	// %TypedArray%
	TypedArrayConstructor ObjectType
	// %TypedArray.prototype%
	TypedArrayPrototype ObjectType
	// %BigInt64Array%
	BigInt64ArrayConstructor ObjectType
	// %BigInt64Array.prototype%
	BigInt64ArrayPrototype ObjectType
	// %BigUint64Array%
	BigUint64ArrayConstructor ObjectType
	// %BigUint64Array.prototype%
	BigUint64ArrayPrototype ObjectType
	// %Float32Array%
	Float32ArrayConstructor ObjectType
	// %Float32Array.prototype%
	Float32ArrayPrototype ObjectType
	// %Float64Array%
	Float64ArrayConstructor ObjectType
	// %Float64Array.prototype%
	Float64ArrayPrototype ObjectType
	// %Int8Array%
	Int8ArrayConstructor ObjectType
	// %Int8Array.prototype%
	Int8ArrayPrototype ObjectType
	// %Int16Array%
	Int16ArrayConstructor ObjectType
	// %Int16Array.prototype%
	Int16ArrayPrototype ObjectType
	// %Int32Array%
	Int32ArrayConstructor ObjectType
	// %Int32Array.prototype%
	Int32ArrayPrototype ObjectType
	// %Uint8Array%
	Uint8ArrayConstructor ObjectType
	// %Uint8Array.prototype%
	Uint8ArrayPrototype ObjectType
	// %Uint8ClampedArray%
	Uint8ClampedArrayConstructor ObjectType
	// %Uint8ClampedArray.prototype%
	Uint8ClampedArrayPrototype ObjectType
	// %Uint16Array%
	Uint16ArrayConstructor ObjectType
	// %Uint16Array.prototype%
	Uint16ArrayPrototype ObjectType
	// %Uint32Array%
	Uint32ArrayConstructor ObjectType
	// %Uint32Array.prototype%
	Uint32ArrayPrototype ObjectType
	// %IsFinite%
	IsFinite ObjectType
	// %isNaN%
	IsNaN ObjectType
	// %eval%
	Eval ObjectType
	// %parseInt%
	ParseInt ObjectType
	// %parseFloat%
	ParseFloat ObjectType
	// %decodeURI%
	DecodeURI ObjectType
	// %decodeURIComponent%
	DecodeURIComponent ObjectType
	// %encodeURI%
	EncodeURI ObjectType
	// %encodeURIComponent%
	EncodeURIComponent ObjectType
	// %RegExp%
	RegExpConstructor ObjectType
	// %RegExp.prototype%
	RegExpPrototype ObjectType
	// %RegExpStringIteratorPrototype%
	RegExpStringIteratorPrototype ObjectType
	// %EvalError%
	EvalErrorConstructor ObjectType
	// %EvalError.prototype%
	EvalErrorPrototype ObjectType
	// %RangeError%
	RangeErrorConstructor ObjectType
	// %RangeError.prototype%
	RangeErrorPrototype ObjectType
	// %ReferenceError%
	ReferenceErrorConstructor ObjectType
	// %ReferenceError.prototype%
	ReferenceErrorPrototype ObjectType
	// %SyntaxError%
	SyntaxErrorConstructor ObjectType
	// %SyntaxError.prototype%
	SyntaxErrorPrototype ObjectType
	// %TypeError%
	TypeErrorConstructor ObjectType
	// %TypeError.prototype%
	TypeErrorPrototype ObjectType
	// %URIError%
	URIErrorConstructor ObjectType
	// %URIError.prototype%
	URIErrorPrototype ObjectType
	// %Error%
	ErrorConstructor ObjectType
	// %Error.prototype%
	ErrorPrototype ObjectType
	// %ThrowTypeError%
	ThrowTypeError ObjectType
	// %AggregateError%
	AggregateErrorConstructor ObjectType
	// %AggregateError.prototype%
	AggregateErrorPrototype ObjectType
}

func (i *Intrinsics) Get(key string) ObjectType {
	switch key {
	case "%Object.Prototype%":
		return i.ObjectPrototype
	case "%Object%":
		return i.ObjectConstructor
	case "%Function.Prototype%":
		return i.FunctionPrototype
	case "%Function%":
		return i.FunctionConstructor
	case "%Boolean.Prototype%":
		return i.BooleanPrototype
	case "%Boolean%":
		return i.BooleanConstructor
	case "%IsFinite%":
		return i.IsFinite
	case "%isNaN%":
		return i.IsNaN
	case "%eval%":
		return i.Eval
	case "%ThrowTypeError%":
		return i.ThrowTypeError
	case "%Array%":
		return i.ArrayConstructor
	case "%Array.Prototype%":
		return i.ArrayPrototype
	case "%String.Prototype%":
		return i.StringPrototype
	case "%String%":
		return i.StringConstructor
	case "%Number.Prototype%":
		return i.NumberPrototype
	case "%Number%":
		return i.NumberConstructor
	case "%Symbol.Prototype%":
		return i.SymbolPrototype
	case "%Symbol%":
		return i.SymbolConstructor
	case "%BigInt.Prototype%":
		return i.BigIntPrototype
	case "%BigInt%":
		return i.BigIntConstructor
	case "%JSON%":
		return i.JSON
	case "%BigInt64Array%":
		return i.BigInt64ArrayConstructor
	case "%BigInt64Array.prototype%":
		return i.BigInt64ArrayPrototype
	case "%BigUint64Array%":
		return i.BigUint64ArrayConstructor
	case "%BigUint64Array.prototype%":
		return i.BigUint64ArrayPrototype
	case "%Float32Array%":
		return i.Float32ArrayConstructor
	case "%Float32Array.prototype%":
		return i.Float32ArrayPrototype
	case "%Float64Array%":
		return i.Float64ArrayConstructor
	case "%Float64Array.prototype%":
		return i.Float64ArrayPrototype
	case "%Int8Array%":
		return i.Int8ArrayConstructor
	case "%Int8Array.prototype%":
		return i.Int8ArrayPrototype
	case "%Int16Array%":
		return i.Int16ArrayConstructor
	case "%Int16Array.prototype%":
		return i.Int16ArrayPrototype
	case "%Int32Array%":
		return i.Int32ArrayConstructor
	case "%Int32Array.prototype%":
		return i.Int32ArrayPrototype
	case "%Uint8Array%":
		return i.Uint8ArrayConstructor
	case "%Uint8Array.prototype%":
		return i.Uint8ArrayPrototype
	case "%Uint8ClampedArray%":
		return i.Uint8ClampedArrayConstructor
	case "%Uint8ClampedArray.prototype%":
		return i.Uint8ClampedArrayPrototype
	case "%Uint16Array%":
		return i.Uint16ArrayConstructor
	case "%Uint16Array.prototype%":
		return i.Uint16ArrayPrototype
	case "%Uint32Array%":
		return i.Uint32ArrayConstructor
	case "%Uint32Array.prototype%":
		return i.Uint32ArrayPrototype
	case "%EvalError%":
		return i.EvalErrorConstructor
	case "%EvalError.prototype%":
		return i.EvalErrorPrototype
	case "%RangeError%":
		return i.RangeErrorConstructor
	case "%RangeError.prototype%":
		return i.RangeErrorPrototype
	case "%ReferenceError%":
		return i.ReferenceErrorConstructor
	case "%ReferenceError.prototype%":
		return i.ReferenceErrorPrototype
	case "%SyntaxError%":
		return i.SyntaxErrorConstructor
	case "%SyntaxError.prototype%":
		return i.SyntaxErrorPrototype
	case "%TypeError%":
		return i.TypeErrorConstructor
	case "%TypeError.prototype%":
		return i.TypeErrorPrototype
	case "%URIError%":
		return i.URIErrorConstructor
	case "%URIError.prototype%":
		return i.URIErrorPrototype
	case "%Error%":
		return i.ErrorConstructor
	case "%Error.prototype%":
		return i.ErrorPrototype
	case "%AggregateError%":
		return i.AggregateErrorConstructor
	case "%AggregateError.prototype%":
		return i.AggregateErrorPrototype

	}
	panic("unknown intrinsic")
}
